### PR TITLE
Add caveat about correlated variables to README.md

### PR DESCRIPTION
**Pull request by ibab**

### CODE REVIEW

**Comment by KonstantinSchubert** [comment]
your updated text suggests that no correlation between PID variables is maintained
this isn't correct as we still get a correlation via the kinematic variables
9:57
and I wouldn't be so specific about PIDp and PIDK, let's let the reader think

**Comment by KonstantinSchubert** [comment]
Maybe:

"Some PID variables, e.g. PIDp and PIDK, are correlated even among events in a single dynamic bin. This package does not take into account this kind of correlation, because it resamples each PID variable independently. "

**Comment by KonstantinSchubert** [comment]
And then maybe, on top:
Nevertheless, the resampled PID variables are still correlated via their dependency on the dynamic of the event.

**Comment by ibab** [comment]
I'm not sure I would understand that explanation.
How about

> This package resamples PID variables one by one, and thus cannot take into account correlations between them. (Except those that already originate from correlations to the kinematic variables that we resample from)

**Comment by KonstantinSchubert** [comment]
I am afraid that this doesn't make it clear enough that the tool does fact
create some correlation between the resampled variables and that secondly,
(as was my observation yesterday) that this covers in fact most of the
correlation.

2015-08-14 22:16 GMT+02:00 Igor Babuschkin notifications@github.com:

**Comment by KonstantinSchubert** [comment]
But I agree my formulation should be improved :)

2015-08-15 13:14 GMT+02:00 Konstantin Schubert <
schubert.konstantin@gmail.com>:

**Comment by KonstantinSchubert** [comment]
How about the following:

The implementation retains not all correlations between PID variables, because it resamples them independently.
This can be important if PIDp and PIK are used at the same time, as these two variables are often significantly correlated in data.

**Comment by KonstantinSchubert** [comment]
Okay, let's agree on the following, which is pretty close to your second suggestion.

> This package resamples PID variables one by one. Therefore it doesn't reflect the correlations between them, except for those that already originate from correlations to the kinematic variables that we resample from.

Would you like to change this in your PR and I merge it? Or shall I just change it directly on the master via github?

**Comment by ibab** [comment]
Okay, I've modified the text

**Pull request merged**
